[package]
name = "eventific"
version = "0.1.18"
edition = '2018'
license = "MIT"
repository = "https://github.com/Joatin/eventific"
homepage = "https://github.com/Joatin/eventific"
description = "Eventific is a tool that gives you the needed building blocks for event sourcing"
authors = ["Joatin Granlund <granlundjoatin@gmail.com>"]
exclude = ["playground/**/*"]
include = ["Cargo.toml", "src/**/*", "playground/build/**/*"]
readme = "../README.md"
keywords = ["cqrs", "event-sourcing", "tokio", "futures"]
categories = ["asynchronous", "database", "data-structures"]

[[example]]
name = "playground"
required-features = ["playground"]
path = "examples/playground.rs"

[[example]]
name = "grpc"
required-features = ["rpc"]
path = "examples/grpc.rs"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
futures = "0.3"
slog = "2.5"
serde = "1.0"
serde_derive = "1.0"
hyper = { version = "0.13" }
tokio = { version = "0.2", features = ["sync", "time", "signal"] }
colored = "1.8"
strum = "0.15"
lazy_static = "1.4"
prometheus = "0.9"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
sloggers = "0.3"
uuid = { version = "0.8", features = ["v4"]}
strum_macros = "0.15"

