[package]
name = "eventific"
version = "0.1.4"
edition = '2018'
license = "MIT"
repository = "https://github.com/Joatin/eventific"
homepage = "https://github.com/Joatin/eventific"
description = "Eventific is a tool that gives you the needed building blocks for event sourcing"
authors = ["Joatin Granlund <granlundjoatin@gmail.com>"]
exclude = ["playground/**/*"]
include = ["Cargo.toml", "src/**/*", "playground/build/**/*"]
readme = "../README.md"
keywords = ["cqrs", "event-sourcing", "tokio", "futures"]
categories = ["asynchronous", "database", "data-structures"]

[package.metadata.docs.rs]
all-features = true

[features]
playground = ["hyper", "rust-embed"]
with_grpc = ["grpc", "tls-api", "tls-api-stub"]

[[example]]
name = "playground"
required-features = ["playground"]
path = "examples/playground.rs"

[[example]]
name = "grpc"
required-features = ["rpc"]
path = "examples/grpc.rs"

[dependencies]
uuid = { version = "0.7.4", features = ["serde"] }
chrono = { version = "0.4.7", features = ["serde"] }
failure = "0.1.5"
futures = "0.1.28"
slog = "2.5.0"
serde = "1.0.95"
serde_derive = "1.0.95"
hyper = { version = "0.12", optional = true }
tokio = { version = "0.1.22" }
rust-embed = { version = "5.1.0", optional = true, features = ["interpolate-folder-path"] }
grpc = { version = "0.6.1", optional = true }
tls-api-stub = { version = "0.1.0", optional = true }
tls-api = { version = "0.1.0", optional = true }
colored = "1.8"

[dev-dependencies]
tokio = "0.1.22"
sloggers = "0.3.2"
uuid = { version = "0.7.4", features = ["v4"]}
grpcio = { version = "0.4", default-features = false, features = ["protobuf-codec"] }
protobuf = "2.5.0"

[build-dependencies]
walkdir = "2.2.8"
protoc-rust-grpc = "0.6.1"
