[package]
name = "eventific"
version = "0.1.0"
edition = '2018'

[dependencies]
uuid = "0.7.4"
chrono = "0.4.7"
failure = "0.1.5"
futures = "0.1.28"
slog = "2.5.1"

[dev-dependencies]
tokio = "0.1.22"
sloggers = "0.3.2"
uuid = { version = "0.7.4", features = ["v4"]}
