language: node_js
sudo: false
node_js:
  - "9"
install:
  - yarn
  - yarn bootstrap
script:
  - yarn test:ci
deploy:
  - provider: script
    script: yarn ci:publish:dev
    on:
      branch: develop
  - provider: script
    script: yarn ci:publish
    on:
      branch: master