language: rust
services:
  - docker
cache:
  yarn: true
  cargo: true
rust:
  - stable
  - beta
  - nightly
env:
  - NODE_VERSION=11 CC=clang CXX=clang++ PATH=$HOME/protoc/bin:$PATH
before_install:
  - nvm install $NODE_VERSION
  - go get -v -d google.golang.org/grpc
  - go get -v -d -t github.com/golang/protobuf/...
  - curl -L https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
install:
  - cd eventific/playground && yarn
before_script:
  - docker-compose up -d
script:
  - cargo build --no-default-features
  - cargo build --all-features
  - cargo test --all-features
after_script:
  - docker-compose down
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
deploy:
  - provider: cargo
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux"
      branch: master
