language: node_js
sudo: required
services:
  - docker
node_js:
  - '8.9.1'
cache:
  yarn: true
  directories:
    - ./node_modules
install:
  - ./scripts/ci/install.sh

script:
  - ./scripts/ci/build.sh
  - ./scripts/ci/test.sh
  # deploy is part of 'script' and not 'after_success' so that we fail the build if the deployment fails
  - ./scripts/ci/deploy.sh
