language: rust
cache:
  yarn: true
  cargo: true
rust:
  - stable
  - beta
  - nightly
env:
  - NODE_VERSION=11 CC=clang CXX=clang++
before_install:
  - nvm install $NODE_VERSION
install:
  - cd eventific/playground && yarn
script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose --all-features
  - cargo test
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
