language: node_js
sudo: false
node_js:
  - "9"
cache: yarn
directories:
  - node_modules
stages:
  - Install Dependencies
  - Test
  - name: Deploy Canary
    if: branch = develop
  - name: Deploy
    if: branch = master
jobs:
  include:
    - stage: Install Dependencies
      script:
        - yarn
        - yarn bootstrap
    - stage: Test
      script:
        - yarn test:ci
    - stage: Deploy Canary
      script:
        - yarn
        - yarn bootstrap
        - yarn ci:publish:dev
    - stage: Deploy
      script:
        - yarn
        - yarn bootstrap
        - yarn ci:publish