language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
install:
  - cd eventific/playground && yarn
before_script:
  - cd eventific/playground && yarn build
script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose --all-features
  - cargo test
deploy:
  provider: cargo
  token: "YOUR_API_TOKEN"
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
