version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4576:4576'
      - '4575:4575'
      - '8089:8089'
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - PORT_WEB_UI=8089
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./.config/localstack-data/:/tmp/localstack
      - ./.config/localstack-init/:/docker-entrypoint-initaws.d/
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./.config/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
