title: Eventific
baseurl: /eventific
collections:
  docs: {output: true, permalink: '/docs/:path/'}
  api: {output: true, permalink: '/api/:path/'}
languages:
  - en
default_lang: en
include:
  - _pages
  - _api
exclude:
  - README.md
  - CNAME
optional_front_matter:
  remove_originals: true

