version: '2'
services:
  mongodb:
    image: mongo:latest
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles #--logpath=/dev/null # --quiet
    logging:
      driver: none
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    tty: true
    logging:
      driver: none
